"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(str(BASE_DIR / ".env"))  # Load .env file

SECRET_KEY = os.getenv("SECRET_KEY")
DEBUG = os.getenv("DEBUG", "False") == "False"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY: ensure secret & debug come from environment in deployment

ALLOWED_HOSTS = ['.onrender.com']  # For development - restrict in production

# Custom authentication backend
AUTHENTICATION_BACKENDS = [
    'admin.auth_backend.ProfileBackend',  # Custom backend for Profile/UserProfile
    'django.contrib.auth.backends.ModelBackend',  # Default Django auth
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',  # CORS middleware
    'admin.apps.AdminConfig',
    'trainer.apps.TrainerConfig',
    # 'trainee.apps.TraineeConfig',  # Removed - marked as "reference but no use", causes table conflicts
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS Middleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    # 'django.middleware.clickjacking.XFrameOptionsMiddleware',  # Disabled for PDF iframe display
    'myproject.middleware.DisableXFrameOptionsMiddleware',  # Custom middleware to remove X-Frame-Options
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.postgresql",
#         # Default DB name set to LMS to match provided DDL; override via .env
#         "NAME": os.getenv("DB_NAME", "LMS"),
#         "USER": os.getenv("DB_USER", "postgres"),
#         "PASSWORD": os.getenv("DB_PASSWORD", "admin@123"),
#         "HOST": os.getenv("DB_HOST", "localhost"),
#         "PORT": os.getenv("DB_PORT", "5432"),
#     }
# }
DATABASES = {
    DATABASES = {
    'default': dj_database_url.config(default=os.environ.get('postgresql://postgres1:ceAtZ1CTnyje4R6nAWJtnTPHqLX1fKFF@dpg-d668jqi48b3s73eogj60-a/lms_back'))
}

}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = r'C:\LMS_uploads'

# Allow iframes from same origin (needed for PDF/media display in frontend)
X_FRAME_OPTIONS = 'SAMEORIGIN'

# Django REST Framework defaults (sane for development)
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# Ensure all database operations in a request are atomic
DATABASES['default']['ATOMIC_REQUESTS'] = True

# CORS / cookie settings for local development
# Prefer listing allowed origins when sending credentials. Do NOT use this in production.
CORS_ALLOW_ALL_ORIGINS = False  # Set to False to explicitly specify allowed origins

# Add frontend origins that are allowed to communicate with the backend
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',  # React dev server for frontend (port 5173)
    'http://127.0.0.1:5173',  # React dev server for frontend (port 5173)
    'http://localhost:3000',   # Another possible dev server (if used)
    'http://localhost:8080',   # Your frontend's domain (add this line)
    'http://localhost:8081',   # Vite dev server with fallback port
    'http://127.0.0.1:8081',   # Vite dev server with fallback port (localhost)
    'http://localhost:8082',   # Trainer app (current running port)
    'http://127.0.0.1:8082',   # Trainer app (current running port - localhost)
]

# Allow cookies/credentials to be sent from the frontend during development
CORS_ALLOW_CREDENTIALS = True

# Ensure session / CSRF cookies can be sent on cross-site requests during local dev.
# These relaxations are for development only — do NOT enable in production.
SESSION_COOKIE_SAMESITE = None
CSRF_COOKIE_SAMESITE = None
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
