# Generated by Django 4.2 on 2026-02-06 14:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.UUIDField(db_column='team_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='team_name', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, db_column='description')),
                ('status', models.CharField(db_column='status', default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'teams',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(db_column='user_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='first_name', max_length=100)),
                ('last_name', models.CharField(db_column='last_name', max_length=100)),
                ('email', models.EmailField(db_column='email', max_length=254, unique=True)),
                ('password_hash', models.CharField(db_column='password_hash', max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('trainer', 'Trainer'), ('trainee', 'Trainee')], db_column='primary_role', default='trainee', max_length=20)),
                ('status', models.CharField(db_column='status', default='active', max_length=20)),
                ('profile_image_url', models.TextField(blank=True, db_column='profile_image_url', null=True)),
                ('last_login', models.DateTimeField(blank=True, db_column='last_login', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myproject_admin.userprofile')),
                ('is_primary_team', models.BooleanField(db_column='is_primary_team', default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True, db_column='assigned_at')),
                ('assigned_by', models.CharField(blank=True, db_column='assigned_by', max_length=255, null=True)),
                ('team', models.ForeignKey(db_column='team_id', on_delete=django.db.models.deletion.CASCADE, to='myproject_admin.team')),
            ],
            options={
                'db_table': 'team_members',
                'managed': True,
                'unique_together': {('team', 'user')},
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='members', through='myproject_admin.TeamMember', to='myproject_admin.team'),
        ),
        migrations.CreateModel(
            name='CourseAssignment',
            fields=[
                ('assignment_id', models.UUIDField(db_column='assignment_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_id', models.CharField(db_column='course_id', help_text='External LMS course id', max_length=255)),
                ('assigned_at', models.DateTimeField(auto_now_add=True, db_column='assigned_at')),
                ('team', models.ForeignKey(db_column='assigned_to_team_id', on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='myproject_admin.team')),
            ],
            options={
                'db_table': 'course_assignments',
                'managed': True,
                'unique_together': {('course_id', 'team')},
            },
        ),
    ]
